# Generated by Django 5.2.17 on 2026-08-15 20:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_date', '-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('repetitions', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight used, in kilograms.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration in seconds.', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('rest_seconds', models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('order', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workout_exercises', to='exercises.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercises', to='workouts.workout')),
            ],
            options={
                'ordering': ['workout', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['user'], name='workout_user_idx'),
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['scheduled_date'], name='workout_sched_date_idx'),
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['status'], name='workout_status_idx'),
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['user', 'scheduled_date'], name='workout_user_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='workout',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'completed', 'cancelled'])), name='workout_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='workout',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', False), ('status', 'completed')), models.Q(('completed_at__isnull', True), ('status__in', ['pending', 'cancelled'])), _connector='OR'), name='workout_completed_at_matches_status'),
        ),
        migrations.AddIndex(
            model_name='workoutexercise',
            index=models.Index(fields=['workout'], name='workoutexercise_workout_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutexercise',
            index=models.Index(fields=['exercise'], name='workoutexercise_exercise_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutexercise',
            index=models.Index(fields=['workout', 'order'], name='workoutexercise_wk_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='workoutexercise',
            constraint=models.UniqueConstraint(fields=('workout', 'order'), name='unique_order_per_workout'),
        ),
        migrations.AddConstraint(
            model_name='workoutexercise',
            constraint=models.CheckConstraint(condition=models.Q(('sets__gt', 0)), name='workoutexercise_sets_positive'),
        ),
        migrations.AddConstraint(
            model_name='workoutexercise',
            constraint=models.CheckConstraint(condition=models.Q(('repetitions__isnull', True), ('repetitions__gt', 0), _connector='OR'), name='workoutexercise_repetitions_positive'),
        ),
        migrations.AddConstraint(
            model_name='workoutexercise',
            constraint=models.CheckConstraint(condition=models.Q(('weight__isnull', True), ('weight__gte', 0), _connector='OR'), name='workoutexercise_weight_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='workoutexercise',
            constraint=models.CheckConstraint(condition=models.Q(('duration__isnull', True), ('duration__gte', 0), _connector='OR'), name='workoutexercise_duration_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='workoutexercise',
            constraint=models.CheckConstraint(condition=models.Q(('rest_seconds__isnull', True), ('rest_seconds__gte', 0), _connector='OR'), name='workoutexercise_rest_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='workoutexercise',
            constraint=models.CheckConstraint(condition=models.Q(('order__gt', 0)), name='workoutexercise_order_positive'),
        ),
    ]
